name: CI

on:
  push:
    branches-ignore:
      - "releases/**"
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      # We want to see all failures:
      fail-fast: false
      matrix:
        config:
        # [Python version, tox env]
        - ["3.7",   "plone52-py37", "ubuntu-22.04"]
        - ["3.8",   "plone52-py38", "ubuntu-24.04"]
        - ["3.8",   "plone60-py38", "ubuntu-24.04"]
        - ["3.9",   "plone60-py39", "ubuntu-latest"]
    runs-on: ${{ matrix.config[2] }}
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Cache Python Packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          eggs
        key: pypkg-${{ runner.os }}-${{ matrix.config[0] }}-${{ matrix.config[1] }}-${{ hashFiles('setup.*', 'tox.ini', '**/*.cfg') }}
        restore-keys: |
          pypkg-${{ runner.os }}
          pypkg-${{ runner.os }}-${{ matrix.config[0] }}
          pypkg-${{ runner.os }}-${{ matrix.config[0] }}-${{ matrix.config[1] }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox coverage coveralls
    - name: Test
      run: tox -e ${{ matrix.config[1] }}
    - name: Upload coverage data to coveralls.io
      run: coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.config[1] }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Coveralls Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}